### ISSUE TITLE
Add DB dummy file 

### ISSUE THREAD

**Issue by KyungjeCho** [KyungjeCho/ddib_backend#18]
지금 추가해야 할 테이블 더미 \: order, order group, item

나중에 추가해야 할 테이블 \: faq, review, favorites, shopping_cart, wtb, wishlist

**Comment by Junuu** [comment]
INSERT INTO `ddib`.`order_group` (`gid`, `cid`, `orderdate`, `payment`) VALUES ('1', '010-1111-2222', '2018-10-04 18:30:00', 'creditcard');
INSERT INTO `ddib`.`order_group` (`gid`, `cid`, `orderdate`, `payment`) VALUES ('2', '010-3333-2222', '2018-10-04 19:30:00', 'visit');

**Comment by Junuu** [comment]
INSERT INTO `ddib`.`order` (`oid`, `iid`, `amount`, `orderstate`, `gid`) VALUES ('1', '1', '2', 'waiting', '20181102001');
INSERT INTO `ddib`.`order` (`oid`, `iid`, `amount`, `orderstate`, `gid`) VALUES ('2', '4', '1', 'cooking', '20181102001');
INSERT INTO `ddib`.`order` (`oid`, `iid`, `amount`, `orderstate`, `gid`) VALUES ('3', '2', '2', 'cooked', '20181102002');
INSERT INTO `ddib`.`order` (`oid`, `iid`, `amount`, `orderstate`, `gid`) VALUES ('4', '3', '1', 'delivering', '20181102002');
INSERT INTO `ddib`.`order` (`oid`, `iid`, `amount`, `orderstate`, `gid`) VALUES ('5', '5', '1', 'complete', '20181102002');
